variables:
  - name: project_name
    value: "vmsscicd"

jobs:
  - job: "Running on Windows"
    pool:
      vmImage: "windows-latest"
    steps:
      - checkout: none
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'Write-Host "This is me running PowerShell code!"' ## Windows PowerShell by default
      - powershell: 'Write-Host "This is me running PowerShell code!"' ## Windows PowerShell
      - pwsh: 'Write-Host "This is me running PowerShell code!"' ## PowerShell Core