# variables:
#   - name: project_name
#     value: "vmsscicd"

# jobs:
#   - job: Running_on_Windows
#     pool:
#       vmImage: "windows-latest"
#     steps:
#       - checkout: none
#       - task: PowerShell@2
#         inputs:
#           targetType: 'inline'
#           script: 'Write-Host "This is me running PowerShell code!"' ## Windows PowerShell by default
#       - powershell: 'Write-Host "This is me running PowerShell code!"' ## Windows PowerShell
#       - pwsh: 'Write-Host "This is me running PowerShell code!"' ## PowerShell Core
#   - job: Running_on_Linux
#     pool:
#       vmImage: "ubuntu-latest"
#     steps:
#       - checkout: none
#       - task: PowerShell@2
#         inputs:
#           targetType: 'inline'
#           script: 'Write-Host "This is me running PowerShell code!"' ## PowerShell (Core) now since on Linux
#       - powershell: 'Write-Host "This is me running PowerShell code!"' ## PowerShell (Core) now since on Linux
#       - pwsh: 'Write-Host "This is me running PowerShell code!"' ## PowerShell (Core) explicitly

steps:
  # - task: PowerShell@2
  #   inputs:
  #     targetType: 'inline'
  #     script: 'Write-Host "This is me running PowerShell code!"'
  #     pwsh: true
  # - powershell: "Get-ChildItem '$(System.DefaultWorkingDirectory)'"
  # - task: PowerShell@2
  #   inputs:
  #     targetType: 'filePath'
  #     filePath: '$(System.DefaultWorkingDirectory)/script_no_params.ps1'
  # - task: PowerShell@2
  #   inputs:
  #     targetType: 'filePath'
  #     filePath: '$(System.DefaultWorkingDirectory)/script.ps1'
  #     arguments: "-foo 'foovalue' -bar 'barvalue'"
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: '$(System.DefaultWorkingDirectory)/soft_error.ps1'
      errorActionPreference: continue